### ISSUE TITLE
NodePoppler.h:5:10: fatal error

### ISSUE THREAD

**Issue by gatodeveloper** [tpisto/pdf-fill-form#23]
I have a issue trying install npm module 

My Steps 

1. $ brew update
2. $ brew install qt5 cairo poppler --with-qt5
3. $ brew linkapps qt5
4. $ brew link --force qt5

Up to this point no errors install, but when I try install npm module 

````
$ npm install pdf-fill-form
````

```
  CXX(target) Release/obj.target/pdf_fill_form/src/pdf-fill-form.o
In file included from ../src/pdf-fill-form.cc:2:
../src/NodePoppler.h:5:10: fatal error: 'QtCore/QBuffer' file not found
#include <QtCore/QBuffer>
         ^
1 error generated.
```

Extra info:

MacOs: Sierra 10.12
NODE version: v6.3.0

**Comment by MichaelBuen** [comment]
I was able to make it work, spent almost eight hours making it work. 

It's not enough that Xcode is installed, I even upgraded from Xcode 7.2 to 8.x, but it's not working. Turns out what solves my problem now with QtCore/QBuffer header is the same solution from my [previous problem](https://github.com/tpisto/pdf-fill-form/issues/16#issuecomment-236362645) with pdf-fill-form 2.x, Xcode commandline tools must be installed.

Do this:

```$ xcode-select --install```

Then before doing ```npm install pdf-fill-form```, export these variables:

```
export LDFLAGS=-L/usr/local/opt/qt5/lib
export CPPFLAGS=-I/usr/local/opt/qt5/include
export PKG_CONFIG_PATH=/usr/local/opt/qt5/lib/pkgconfig
```

Just doing export variables and not doing ```xcode-select --install```, and vice versa, won't solve the missing 'QtCore/QBuffer' problem.

```brew linkapps qt5``` and ```brew link --force qt5``` need not be applied

**Comment by sandman45** [comment]
@MichaelBuen thanks! that worked for me.. I did

`$ xcode-select --install`
`$ export LDFLAGS=-L/usr/local/opt/qt5/lib
$ export CPPFLAGS=-I/usr/local/opt/qt5/include
$ export PKG_CONFIG_PATH=/usr/local/opt/qt5/lib/pkgconfig`

then npm install.. and no errors thanks

**Comment by tpisto** [comment]
@MichaelBuen Thank you for your time sharing that good piece of nformation. Please could you write your observations also to this projects readme -file. Thank you!

**Comment by aconran** [comment]
Thank you @MichaelBuen !

**Comment by fengsi** [comment]
Same error happened on FreeBSD 11.0-RELEASE

**Comment by Sigura** [comment]
was enough for me:

`xcode-select --install`

**Comment by gatodeveloper** [comment]
@MichaelBuen Thanks for your time, So I'll close it issue.
