### ISSUE TITLE
Pass in buffer object?

### ISSUE THREAD

**Issue by tyleriguchi** [tpisto/pdf-fill-form#4]
Hey I'm playing around with the library, and was wondering if it's possible to pass in a buffer object to the read method or if it needs to a pdf file.

**Comment by tpisto** [comment]
Hi - currently it needs the pdf file since internally it's using the Poppler::Document::load(**fileName). Poppler has method loadFromData (const QByteArray &fileContents, const QByteArray &ownerPassword=QByteArray(), const QByteArray &userPassword=QByteArray()), so in theory it's possible to create also support for buffer objects.

**Comment by tyleriguchi** [comment]
Ah cool, thanks!
