### ISSUE TITLE
Not filling out forms

### ISSUE THREAD

**Issue by senica** [tpisto/pdf-fill-form#48]
I get the fields and it looks like this:
```
{ name: 'form1[0].#subform[0]﻿.Line2b_GivenName[0]',
       page: 0,
       value: '',
       id: 65540,
       type: 'text' }
```

But if I use 
```
let result = await pdf.write( source, {
  'form1[0].#subform[0]﻿.Line2b_GivenName[0]': 'senica'
}, {save: 'pdf'});
```

It does not fill in the form. I've tried several different fields. No errors are thrown and the returned pdf (after I save the result) is able to be opened just fine. It's just not filled in.

I've attached a test file I'm using.

Any thoughts?

[g-28.pdf](https://github.com/tpisto/pdf-fill-form/files/1432580/g-28.pdf)

**Comment by shairozan** [comment]
Just a thought, but it might be because that document is protected. I've had similar issues with the IRS AIR PDFs. Here's what I'd recommend trying:

1. Render that PDF down to an image
2. Create a new PDF from that image
3. Try adding a custom field do it
4. Try filling the new custom field

If that works, I'd finish building the fields out on the form with new custom fields.
